/**
 * Static product seed — mirrors the DB seed.
 * Used as fallback when Supabase is not configured yet.
 */
import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "mix-europeo",
    name: "Mix Europeo",
    category: "frutos",
    cat_label: "Frutos secos",
    price: 13000,
    unit: "kg",
    stock_kg: 5,
    low_threshold: 2,
    status: "disponible",
    image_url: "/img/mix-europeo-x-kilo.jpg",
    image_webp_url: "/img/mix-europeo-x-kilo.webp",
    image_400_url: "/img/mix-europeo-x-kilo-400.webp",
    copy: "Maní sin sal, almendras, nueces y avellanas. La mezcla que desaparece primero de la mesa.",
    badge: "Top ventas",
    sort_order: 1,
    color: "orange",
    min_unit_kg: 1,
  },
  {
    id: "2",
    slug: "mani-confitado-tropical",
    name: "Maní Confitado Tropical",
    category: "dulces",
    cat_label: "Dulces",
    price: 5990,
    unit: "kg",
    stock_kg: 5,
    low_threshold: 2,
    status: "disponible",
    image_url: "/img/mani-confitado-tropical-x-kilo.jpg",
    image_webp_url: "/img/mani-confitado-tropical-x-kilo.webp",
    image_400_url: "/img/mani-confitado-tropical-x-kilo-400.webp",
    copy: "Maní envuelto en azúcar de colores. Crujiente, dulce, imposible parar.",
    badge: null,
    sort_order: 2,
    color: "green",
    min_unit_kg: 1,
  },
  {
    id: "3",
    slug: "mani-confitado-rojo",
    name: "Maní Confitado Rojo",
    category: "dulces",
    cat_label: "Dulces",
    price: 5990,
    unit: "kg",
    stock_kg: 5,
    low_threshold: 2,
    status: "disponible",
    image_url: "/img/mani-confitado-natural-rojo-x-kilo.jpg",
    image_webp_url: "/img/mani-confitado-natural-rojo-x-kilo.webp",
    image_400_url: "/img/mani-confitado-natural-rojo-x-kilo-400.webp",
    copy: "El confitado clásico. Rojo oscuro, crujiente por fuera, maní tostado por dentro.",
    badge: null,
    sort_order: 3,
    color: "red",
    min_unit_kg: 1,
  },
  {
    id: "4",
    slug: "chuby-bardu",
    name: "Chuby Bardú",
    category: "dulces",
    cat_label: "Dulces",
    price: 9990,
    unit: "kg",
    stock_kg: 5,
    low_threshold: 2,
    status: "disponible",
    image_url: "/img/chuby-bardu-x-kilo-.jpg",
    image_webp_url: "/img/chuby-bardu-x-kilo-.webp",
    image_400_url: "/img/chuby-bardu-x-kilo--400.webp",
    copy: "Confites de chocolate en todos los colores. Los que desaparecen del bowl sin que nadie confiese.",
    badge: "Popular",
    sort_order: 4,
    color: "purple",
    min_unit_kg: 1,
  },
  {
    id: "5",
    slug: "gomita-osito-docile",
    name: "Gomita Osito Docile",
    category: "dulces",
    cat_label: "Dulces",
    price: 8500,
    unit: "kg",
    stock_kg: 5,
    low_threshold: 2,
    status: "disponible",
    image_url: "/img/gomita-osito-docile-x-kg.jpg",
    image_webp_url: "/img/gomita-osito-docile-x-kg.webp",
    image_400_url: "/img/gomita-osito-docile-x-kg-400.webp",
    copy: "Ositos de goma suaves. Los comes de a uno y cuando cachái se acabaron.",
    badge: null,
    sort_order: 5,
    color: "yellow",
    min_unit_kg: 1,
  },
  {
    id: "6",
    slug: "almendra-entera",
    name: "Almendra Entera",
    category: "frutos",
    cat_label: "Frutos secos",
    price: 14990,
    unit: "kg",
    stock_kg: 1,
    low_threshold: 2,
    status: "ultimo_kg",
    image_url: "/img/saco-almendra-enteras-x-10-kilos.jpg",
    image_webp_url: "/img/saco-almendra-enteras-x-10-kilos.webp",
    image_400_url: "/img/saco-almendra-enteras-x-10-kilos-400.webp",
    copy: "Almendra natural con piel. Crujiente, nutritiva, de primera. Solo queda un kilo.",
    badge: "Último kg",
    sort_order: 6,
    color: "sand",
    min_unit_kg: 1,
  },
];

export function fmt(n: number): string {
  return "$" + n.toLocaleString("es-CL");
}

// Re-exported from business-info — source of truth is there
export { WA } from "./business-info";
